# Use official Node image
FROM node:18

# Set working directory
WORKDIR /app

# Install deps
COPY package.json package-lock.json ./
RUN npm install

# Copy remaining source code
COPY . .

# Expose React port
EXPOSE 3000

# Start app
CMD ["npm", "start"]